# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
# IP: The module: 'system_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
# IP: The module: 'system_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/XilinxProjects/redpitaya-fpga-example-template/adc_dac_control.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
